# To start sidekiq run "bundle exec sidekiq".
# Use https://crontab.guru/ for cron schedule expressions.

:dynamic: true
:schedule:
  TrialEndingWorker:
    cron: '0 4 * * *' # "At 04:00."

  DeeplSupportedLanguagesWorker:
    cron: '0 4 * * *' # "At 04:00."

  ResetMachineTranslationCharactersUsageWorker:
    cron: '0 4 1 * *' # "At 04:00 on day-of-month 1."

:queues:
  - active_storage_analysis
  - active_storage_purge
  - default
