name: Reusable test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      DB_TEST_HOST: db
      DB_TEST_USERNAME: postgres
      SECRET_KEY_BASE: 8dfc55709e6daaf5d7b2ce70e247374400f47db2e4b6867f67821290b440a0acbe931d5f4d9687f386e5aae3f0377da533450058e131b37dbc16b692c296c941
    steps:
      - uses: actions/checkout@v3

      - name: Install docker-compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0
          legacy: true # will also install in PATH as `docker-compose`

      - name: Run docker-compose
        run: docker-compose up -d

      - name: Create and seed test database
        run: docker-compose exec -T app bundle exec rails db:create db:migrate db:seed RAILS_ENV=test

      - name: Run linters
        run: docker-compose exec -T app yarn lint

      - name: Run tests
        run: docker-compose exec -T app yarn test

      - name: Check database consistency
        run: docker-compose exec -T app yarn check:database-consistency:test

      - name: Send notification to Slack if job fails
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
